[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name="aloedav"
version = "0.1.0"
description = ""
authors = [{email = "michael@aloecraft.org"}]
maintainers = [{email = "michael@aloecraft.org"}]
readme = "README.md"
requires-python = ">=3.9"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

# This tells setuptools to look for dependencies in your specific file
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["config/requirements.txt"]}

[tool.setuptools.packages.find]
where = ["src"]
include = ["aloedav*"]
namespaces = false # Set to true if you plan to use namespace packages later